### ISSUE TITLE
Тестовая программа на Arduino

### ISSUE THREAD

**Issue by baseleo** [n7nexus/PRIRES-M#2]

**Comment by n7nexus** [comment]
Светодиоды на реле зажигаются от логического нуля, подаваемого с ардуино. 
Думаю, стоит переставить светодиоды в другой разъем (NO - нормально-разомкнутый контакт), чтобы они загорались от логической единицы.

**Comment by Rmnik** [comment]
У релейного модуля оптроны объединены анодами и подключены через перемычку к положительному полюсу (VCC) и поэтому входной сигнал инвертированный, т.е. если на выводе Arduino 1, то реле выключено, а если 0, то включено. Все светодиоды должны быть подключены к контактам 1. 2 контакт общий, 3 нормально зомкнутый, судя по схеме.

**Comment by Rmnik** [comment]
http://nn.electronshik.ru/pdf/pdf/4/4%20channel%20relay.pdf

**Comment by baseleo** [comment]
Согласен с Максимом - надо делать включение логическим 0 и ничего не менять.
