### ISSUE TITLE
Класс для расчета оптимальных значений

### ISSUE THREAD

**Issue by n7nexus** [n7nexus/PRIRES-M#4]
Создать класс и, взаимодействуя с Виталиком, добиться получения графика.

**Comment by Hate95** [comment]
Создан классы для начальных оптимальных расчетов расчетов, с поддержкой QT.

**Comment by Hate95** [comment]
Сделал тестовую программу с выводом графиком оптимальных значений!

**Comment by Hate95** [comment]
класс для расчета оптимальных значений сделал singleton-ом!

**Comment by Hate95** [comment]
сделал в тестовой программе сохранение и загрузку настроек через QSetting!

**Comment by n7nexus** [comment]
сделано
